// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Veterinary.CleanArchitecture.Infrastructure.Data;

#nullable disable

namespace Veterinary.CleanArchitecture.Infrastructure.Persistence.Migrations.VeterinaryMigrations
{
    [DbContext(typeof(ApplicationDatabaseContext))]
    partial class ApplicationDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Veterinary.CleanArchitecture.Domain.Entities.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("DateAddedToSystem")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_added_to_system")
                        .HasColumnOrder(4);

                    b.Property<string>("ExtraInformation")
                        .HasColumnType("longtext")
                        .HasColumnName("extra_information")
                        .HasColumnOrder(3);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name")
                        .HasColumnOrder(1);

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("identification")
                        .HasColumnOrder(5);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("phone_number")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("owners");
                });
#pragma warning restore 612, 618
        }
    }
}
